log:
  level: info
  format: json

output:
  dir: dist
  clean: true
  index: true
  not_found: true
  robots: true
  sitemap: true

# this is the root domain where all our packages will be served from
domain: go.treyburn.dev

defaults:
  branch: main
  go_source: true
  redirect_root: https://pkg.go.dev

modules:
  - name: vanity
    repo: https://github.com/treyburn/vanity
  - name: ordered
    repo: https://github.com/treyburn/ordered
  - name: farkle
    repo: https://github.com/treyburn/farkle

templates:
  index: templates/index.html
  partials:
    - templates/header.html
    - templates/footer.html
  assets:
    - css/
    - icons/
