name: Deploy

on:
  repository_dispatch:
    types:
      - vanity-release
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    # don't deploy if this event was triggered by a closed PR that included a `skip-release` label
    if: >-
      github.event_name != 'pull_request' ||
      (github.event.pull_request.merged == true &&
       !contains(github.event.pull_request.labels.*.name, 'skip-release'))
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.1

      - name: Install vanity CLI
        run: go install go.treyburn.dev/vanity@latest

      - name: Generate pages
        run: vanity generate

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=pkgs --branch=main
