name: Label PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .vanity.yml

jobs:
  label:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
    steps:
      - name: Add skip-release label
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr edit "${{ github.event.pull_request.number }}" --repo "$GITHUB_REPOSITORY" --add-label "skip-release"